# Site settings
title: Thomas Punt's Blog
email: tpunt@php.net
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! This is where I'll be sharing my thoughts, experience,
  and knowledge in programming and databases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tpunt94
github_username:  tpunt

# Build settings
markdown: kramdown
